"""Export the standalone appendix directly from the canonical implementation."""

from pathlib import Path


def main() -> None:
    directory = Path(__file__).resolve().parent
    source = (directory / "mechanistic.py").read_text(encoding="utf-8")
    core = source.split("@dataclass(frozen=True)\nclass _Storage:", 1)[0]
    for line in ("from collections import OrderedDict\n", "import io\n",
                 "import pickle\n", "from pathlib import Path\n", "import zipfile\n"):
        core = core.replace(line, "")
    header = "# Generated by export_appendix.py; edit mechanistic.py then regenerate.\n"
    demo = '''
if __name__ == "__main__":
    import json

    policy = MechanisticPolicy(circle_sides=96, angle_step_deg=2.0,
                               safe_angle_step_deg=0.05, safe_guard_m=0.0)
    station = np.array([1700.0, 0.0])
    decision = policy.decide(station, measured_bearing=0.0)
    print(json.dumps({
        "station_m": station.tolist(),
        "first_bearing_deg": 0.0,
        "second_station_m": decision.point.tolist(),
        "sampled_worst_mec_radius_m": decision.score.worst_mec_radius_m,
        "near_optimal_count": int(decision.near_optimal_mask.sum()),
        "candidate_le20_count": int((decision.candidate_scores[:, 0] <= 20).sum()),
    }, indent=2))
'''
    (directory / "appendix_core.py").write_text(header + core.rstrip() + "\n\n" + demo,
                                                 encoding="utf-8")


if __name__ == "__main__":
    main()
